// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4oguB1hm3VFKbygUp0Qx6mTB4UiBjHbI',
    appId: '1:1067306209316:web:b958a2b0c2a50ceddb48b1',
    messagingSenderId: '1067306209316',
    projectId: 'studyproject-4b742',
    authDomain: 'studyproject-4b742.firebaseapp.com',
    databaseURL: 'https://studyproject-4b742-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studyproject-4b742.appspot.com',
    measurementId: 'G-HYLSPKJCPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJkXL_2a2lVHybFb_hpB95UXYfZYdh9A',
    appId: '1:1067306209316:android:7d43c2a1eee8cbc0db48b1',
    messagingSenderId: '1067306209316',
    projectId: 'studyproject-4b742',
    databaseURL: 'https://studyproject-4b742-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studyproject-4b742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcwKdg1F7pChFSTuVbgTkYDynPn2D5y70',
    appId: '1:1067306209316:ios:19d7ba7762abe8ccdb48b1',
    messagingSenderId: '1067306209316',
    projectId: 'studyproject-4b742',
    databaseURL: 'https://studyproject-4b742-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studyproject-4b742.appspot.com',
    iosBundleId: 'com.example.idcProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcwKdg1F7pChFSTuVbgTkYDynPn2D5y70',
    appId: '1:1067306209316:ios:9a81e09a9c3690d9db48b1',
    messagingSenderId: '1067306209316',
    projectId: 'studyproject-4b742',
    databaseURL: 'https://studyproject-4b742-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studyproject-4b742.appspot.com',
    iosBundleId: 'com.example.idcProject.RunnerTests',
  );
}
